#include "../ServerSendBuffer.h"
#include "minorGems/util/SimpleVector.h"
#include "minorGems/util/stringUtils.h"
#include "minorGems/formats/encodingUtils.h"
#include <cassert>
#include <string>
#include <vector>

static int messagesInCount = 0;
static SimpleVector<unsigned char> serverSocketBuffer;
static double game_getCurrentTime() { return 1; }

// Generated by the runner from the existing OneLife client, without edits.
#include "legacyClientMessageParser.inc"

static std::string compressed( const std::string &plain, bool mapChunk=false ) {
    int length = 0;
    unsigned char *binary = zipCompress( (unsigned char*)plain.data(), plain.size(), &length );
    assert( binary != NULL );
    std::string header = mapChunk ? "MC\n2 1 0 0\n" : "CM\n";
    header += std::to_string( plain.size() ) + " " + std::to_string( length ) + "\n#";
    std::string frame = header + std::string( (const char*)binary, length );
    delete [] binary;
    return frame;
    }

static void consume( std::vector<std::string> &received, const std::string &map ) {
    // A CM header deliberately returns NULL once in the old parser, even when
    // its payload is already present. Its normal next game step retries it.
    for( int attempts=0; attempts<64; ++attempts ) {
        char *message = getNextServerMessage();
        if( message == NULL ) {
            if( pendingCMData && serverSocketBuffer.size() >= pendingCMCompressedSize ) continue;
            break;
            }
        if( getMessageType( message ) == MAP_CHUNK ) {
            int plainSize, binarySize;
            assert( sscanf( message, "MC\n%*d %*d %*d %*d\n%d %d\n",
                            &plainSize, &binarySize ) == 2 );
            assert( serverSocketBuffer.size() >= binarySize );
            unsigned char *binary = serverSocketBuffer.getElementArray();
            unsigned char *plain = zipDecompress( binary, binarySize, plainSize );
            assert( plain != NULL );
            assert( std::string( (const char*)plain, plainSize ) == map );
            delete [] plain;
            delete [] binary;
            serverSocketBuffer.deleteStartElements( binarySize );
            received.push_back( "MC" );
            }
        else received.push_back( message );
        delete [] message;
        }
    }

int main() {
    const std::string mx = "MX\n1 2 0 7233 -1\n";
    const std::string player = "PU\n1 2\n";
    const std::string map = "0:0:0 0:0:7233\n";
    const std::string wire = player + "#" + mx + "#FM\n#" +
        compressed( mx ) + "FM\n#" + compressed( map, true ) + mx + "#FM\n#";

    ServerSendBuffer output;
    output.setMessageContext( (const unsigned char*)wire.data(), wire.size(), "legacy", 1 );
    assert( output.enqueue( (const unsigned char*)wire.data(), wire.size(), 1, 0, 1048576 ) );
    std::string delivered;
    double now = 2;
    // Force cuts inside text headers and compressed binary payloads.
    while( output.pending() > 0 ) {
        assert( output.drain( now, 0, 15, 7,
            [&]( const unsigned char *data, int size ) -> ServerWriteResult {
                delivered.append( (const char*)data, size );
                return { size, 0 };
                } ) );
        now += .01;
        }
    assert( delivered == wire );

    for( int frameMode=0; frameMode<2; ++frameMode ) {
        waitForFrameMessages = frameMode;
        for( size_t chunk : { size_t(1), size_t(7), wire.size() } ) {
            std::vector<std::string> received;
            for( size_t offset=0; offset<delivered.size(); offset+=chunk ) {
                size_t count = (std::min)( chunk, delivered.size() - offset );
                serverSocketBuffer.appendArray( (unsigned char*)delivered.data() + offset, count );
                consume( received, map );
                }
            consume( received, map );
            std::vector<std::string> expected = { player, mx };
            if( !frameMode ) expected.push_back( "FM\n" );
            expected.push_back( mx );
            if( !frameMode ) expected.push_back( "FM\n" );
            expected.push_back( "MC" );
            expected.push_back( mx );
            if( !frameMode ) expected.push_back( "FM\n" );
            assert( received == expected );
            assert( serverSocketBuffer.size() == 0 && !pendingCMData && pendingMapChunkMessage == NULL );
            assert( serverFrameMessages.size() == 0 && !serverFrameReady );
            }
        }
    puts( "Existing OneLife client parser: CM/MC/MX/FM passed with 1-byte, 7-byte and merged input" );
    }
